<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="w-full max-w-md space-y-8">
    <div>
      <img class="mx-auto h-24 w-auto" src="../PhotoChaos/img/photochaos_logo_red.jpg" alt="PhotoChaos_logo">
      <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Log in to your account</h2>
    </div>
    <form class="mt-8 space-y-6" action="#" method="POST">
      <input type="hidden" name="remember" value="true">
      <div class="-space-y-px rounded-md shadow-sm">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" autocomplete="username" required class="relative block w-full appearance-none rounded-none rounded-t-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" autocomplete="current-password" required class="relative block w-full appearance-none rounded-none rounded-b-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div class="flex items-center justify-between">
        <div class="flex items-center">
          <input id="remember-me" name="remember-me" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-[#b73c2f] focus:ring-[#cd4934] accent-[#cd4934]">
          <label for="remember-me" class="ml-2 block text-sm text-gray-900">Remember me</label>
        </div>

        <div class="text-sm">
          <a href="#" class="font-medium text-#CD4934 hover:text-[#cd4934]">Forgot your password?</a>
        </div>
      </div>

      <div class="flex w-1/2 justify-center mx-auto gap-2">
        <button type="submit" class="group relative flex w-full justify-center rounded-md border border-transparent bg-[#f6d4c6] py-2 px-4 text-sm font-medium text-white hover:bg-#CD4934 focus:outline-none focus:ring-2 focus:ring-[#cd4934] focus:ring-offset-2">
          Sign up
        </button>
        <button type="submit" class="group relative flex w-full justify-center rounded-md border border-transparent bg-[#b73c2f] py-2 px-4 text-sm font-medium text-white hover:bg-#CD4934 focus:outline-none focus:ring-2 focus:ring-[#cd4934] focus:ring-offset-2">
          Log in
        </button>
      </div>
    </form>
  </div>
</div>