<div class="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="w-full max-w-md space-y-8">
    <div>
      <img class="mx-auto h-24 w-auto" src="../PhotoChaos/img/photochaos_logo_red.jpg" alt="PhotoChaos_logo">
      <h2 class="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign up</h2>
    </div>
    <form class="mt-8 space-y-6" action="#" method="POST">
      <input type="hidden" name="remember" value="true">
      <div class="space-y-2 rounded-lg-md shadow-sm">
        <div>
          <p class="text-sm p-1">Username:</p>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" autocomplete="username" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" placeholder="usernametest">
        </div>
        <div>
          <p class="text-sm p-1">Password:</p>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" autocomplete="current-password" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" placeholder="passtest43">
        </div>
        <div>
          <p class="text-sm p-1">Password confirmation:</p>
          <label for="password" class="sr-only">Confirm Password</label>
          <input id="repeat-password" name="repeat-password" type="password" autocomplete="current-password" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" placeholder="passtest43">
        </div>
        <div>
          <p class="text-sm p-1">First name:</p>
          <label for="firstname" class="sr-only">Firstname</label>
          <input id="firstname" name="firstname" type="text" autocomplete="firstname" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" placeholder="TestName">
        </div>
        <div>
          <p class="text-sm p-1">Last name:</p>
          <label for="lastname" class="sr-only">Lastname</label>
          <input id="lastname" name="lastname" type="text" autocomplete="lastname" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" placeholder="TestLast">
        </div>
        <div>
          <p class="text-sm p-1">Birthday:</p>
          <label for="birthday" class="sr-only">Birthday</label>
          <input id="birthday" name="birthday" type="date" autocomplete="birthday" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm placeholder-gray-400" value="1991-05-11">
        </div>
        <div>
          <p class="text-sm p-1">Email:</p>
          <label for="email" class="sr-only">Email</label>
          <input id="email" name="email" type="email" autocomplete="email" required class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-500 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm" placeholder="test@gmail.com">
        </div>
        <div class="justify-end">
          <p class="text-sm p-1">Profile photo:</p>
          <!-- MAX_FILE_SIZE debe preceder al campo de entrada del fichero -->
          <input type="hidden" name="MAX_FILE_SIZE" value="30000" />
          <!-- El nombre del elemento de entrada determina el nombre en el array $_FILES -->
          <input id="profile_photo" name="profile_photo" type="file" class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] sm:text-sm hidden">
          <label for="profile_photo" class="relative block w-full appearance-none rounded-lg border border-gray-300 px-3 py-2 text-gray-900 focus:z-10 focus:border-[#cd4934] focus:outline-none focus:ring-[#cd4934] hover:text-[#cd4934] sm:text-sm  text-sm font-medium">
          <i class="fa-solid fa-arrow-up-from-bracket"></i> Upload Your Photo</label>
        </div> 
        <div>
        </div>
      </div>

      <div class="text-sm text-right ">
        Do you already have an account? <a href="#" class="font-medium text-#CD4934 hover:text-[#cd4934]">Log in</a>
      </div>

      <div class="flex w-1/2 justify-center mx-auto gap-2">
        <button type="submit" class="group relative flex w-full justify-center rounded-md border border-transparent bg-[#b73c2f] py-2 px-4 text-sm font-medium text-white hover:bg-#CD4934 focus:outline-none focus:ring-2 focus:ring-[#cd4934] focus:ring-offset-2">
          Sign up
        </button>
      </div>
    </form>
  </div>
</div>